import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { useColorScheme } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import i18n from './i18n';

const AppSettingsContext = createContext(null);
const legacyKeys = { brand: 'common.brand', login: 'common.login', home: 'common.home', back: 'common.back', scanner: 'tabs.scanner', dictionary: 'tabs.dictionary', emergency: 'tabs.emergency', profile: 'tabs.profile', forecast: 'main.forecast', beaches: 'main.beaches', nearest: 'main.nearest', loadingWeather: 'main.loadingWeather', sourceKma: 'main.sourceKma', safe: 'main.safe', interest: 'main.interest', caution: 'main.caution', warning: 'main.warning', temperature: 'main.temperature', wind: 'main.wind', weather: 'main.weather', welcomeGuest: 'main.welcomeGuest', scannerHint: 'scanner.hint', camera: 'common.camera', gallery: 'common.gallery', analyzing: 'scanner.analyzing', recentScans: 'scanner.recent', noScans: 'scanner.empty', featureRisk: 'scanner.featuresRisk', actionGuide: 'scanner.actionGuide', emergencyGuide: 'scanner.emergencyGuide', darkMode: 'common.darkMode', language: 'common.language' };

// Semantic tokens: no pure black/white in the dark scheme, with surfaces and
// contrast tuned for long reading sessions in a low-light environment.
export const lightTheme = { background: '#F0FAFC', surface: '#FFFFFF', surfaceRaised: '#F8FCFD', text: '#0A192F', muted: '#607D8B', border: '#D9EEF3', soft: '#E0F2FE', accent: '#00B4D8', accentStrong: '#075985', onAccent: '#062235', danger: '#DC2626', dangerSoft: '#FEF2F2', dangerText: '#991B1B', success: '#15803D', successSoft: '#DCFCE7', warning: '#B45309', warningSoft: '#FEF3C7', skeleton: '#CBD5E1', backdrop: 'rgba(10,25,47,0.58)', shadow: '0 4px 16px rgba(10,25,47,0.10)' };
export const darkTheme = { background: '#121212', surface: '#232323', surfaceRaised: '#2C2C2C', text: '#E2E8F0', muted: '#B8C4D1', border: '#3A4653', soft: '#1B3445', accent: '#38BDF8', accentStrong: '#7DD3FC', onAccent: '#082032', danger: '#FB7185', dangerSoft: '#421D25', dangerText: '#FECDD3', success: '#4ADE80', successSoft: '#163323', warning: '#FBBF24', warningSoft: '#3A2D14', skeleton: '#3B4652', backdrop: 'rgba(0,0,0,0.66)', shadow: '0 3px 12px rgba(0,0,0,0.24)' };
export const oceanTheme = { background: '#062B3A', surface: '#0B4053', surfaceRaised: '#12566B', text: '#E0F7FA', muted: '#B2DFDB', border: '#28677A', soft: '#0B5366', accent: '#2DD4BF', accentStrong: '#99F6E4', onAccent: '#04303A', danger: '#FB7185', dangerSoft: '#4A1E35', dangerText: '#FBCFE8', success: '#5EEAD4', successSoft: '#124A49', warning: '#FCD34D', warningSoft: '#493B17', skeleton: '#276476', backdrop: 'rgba(0,31,44,0.72)', shadow: '0 4px 16px rgba(0,15,22,0.30)' };
export const pastelTheme = { background: '#FFF7FB', surface: '#FFFFFF', surfaceRaised: '#FFF0F7', text: '#493447', muted: '#866E83', border: '#F0D6E5', soft: '#FCE7F3', accent: '#E879A8', accentStrong: '#BE527F', onAccent: '#FFFFFF', danger: '#E76F8F', dangerSoft: '#FFE4EC', dangerText: '#A63D5B', success: '#6FAF9B', successSoft: '#E1F4EE', warning: '#D39A3A', warningSoft: '#FFF2D6', skeleton: '#F0CEE0', backdrop: 'rgba(73,52,71,0.46)', shadow: '0 4px 16px rgba(132,84,112,0.13)' };
export const halloweenTheme = { background: '#21142B', surface: '#332040', surfaceRaised: '#442755', text: '#FCEEF9', muted: '#D7BED8', border: '#664B71', soft: '#40264D', accent: '#FB923C', accentStrong: '#FDBA74', onAccent: '#32120A', danger: '#F43F5E', dangerSoft: '#50172B', dangerText: '#FECDD3', success: '#A3E635', successSoft: '#32451B', warning: '#FACC15', warningSoft: '#493A12', skeleton: '#5C3F67', backdrop: 'rgba(20,10,28,0.72)', shadow: '0 4px 16px rgba(0,0,0,0.35)' };
export const christmasTheme = { background: '#0E2B27', surface: '#173C35', surfaceRaised: '#245248', text: '#EDF9F3', muted: '#B9D8CE', border: '#3B695C', soft: '#1A4B40', accent: '#E85D75', accentStrong: '#FFB3C1', onAccent: '#3A0812', danger: '#F87171', dangerSoft: '#512226', dangerText: '#FECACA', success: '#86EFAC', successSoft: '#1D4932', warning: '#FDE68A', warningSoft: '#4A4020', skeleton: '#37675B', backdrop: 'rgba(6,26,22,0.72)', shadow: '0 4px 16px rgba(0,0,0,0.32)' };
export const cherryBlossomTheme = { background: '#FFF8FC', surface: '#FFFFFF', surfaceRaised: '#FFF0F6', text: '#4E3342', muted: '#8D6E7C', border: '#F3D6E2', soft: '#FCE7F0', accent: '#EC7FA9', accentStrong: '#B94D78', onAccent: '#FFFFFF', danger: '#D95073', dangerSoft: '#FFE4EC', dangerText: '#9D3151', success: '#79AF9B', successSoft: '#E3F4EC', warning: '#D49B41', warningSoft: '#FFF2DA', skeleton: '#F2CEE0', backdrop: 'rgba(78,51,66,0.45)', shadow: '0 4px 16px rgba(182,94,133,0.14)' };
export const nightSeaTheme = { background: '#071B32', surface: '#0D2C4A', surfaceRaised: '#143B60', text: '#E7F1FA', muted: '#B4C9DE', border: '#285071', soft: '#103754', accent: '#5CC8FF', accentStrong: '#A5E4FF', onAccent: '#062238', danger: '#FF7D91', dangerSoft: '#482032', dangerText: '#FFD0D8', success: '#63D8BE', successSoft: '#123E3D', warning: '#FFD166', warningSoft: '#4B3C16', skeleton: '#2B5879', backdrop: 'rgba(2,13,27,0.74)', shadow: '0 4px 16px rgba(0,0,0,0.34)' };
export const arcticTheme = { background: '#EDF8FC', surface: '#FFFFFF', surfaceRaised: '#E5F5FB', text: '#173A4D', muted: '#648397', border: '#C8E5F0', soft: '#DDF3FA', accent: '#42B8E6', accentStrong: '#14799F', onAccent: '#FFFFFF', danger: '#E66D7B', dangerSoft: '#FFE6EB', dangerText: '#9F3A46', success: '#49A891', successSoft: '#DEF3ED', warning: '#D59D3B', warningSoft: '#FFF2D8', skeleton: '#C6E5F0', backdrop: 'rgba(20,75,101,0.43)', shadow: '0 4px 16px rgba(35,108,140,0.12)' };
export const THEMES = { light: lightTheme, dark: darkTheme, ocean: oceanTheme, pastel: pastelTheme, cherry: cherryBlossomTheme, nightSea: nightSeaTheme, arctic: arcticTheme, halloween: halloweenTheme, christmas: christmasTheme };
export const isSeasonalThemeAvailable = (theme, now = new Date()) => (theme === 'halloween' ? now.getMonth() === 9 : theme === 'christmas' ? now.getMonth() === 11 : true);

export function AppSettingsProvider({ children }) {
  const systemScheme = useColorScheme();
  const [theme, setThemeState] = useState('system');
  const [language, setLanguageState] = useState('ko');
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => { AsyncStorage.multiGet(['appTheme', 'appLanguage']).then(([storedTheme, storedLanguage]) => { const candidate = storedTheme[1]; const nextTheme = ['system', ...Object.keys(THEMES)].includes(candidate) && isSeasonalThemeAvailable(candidate) ? candidate : 'system'; setThemeState(nextTheme); const nextLanguage = ['ko', 'en', 'zh', 'ja'].includes(storedLanguage[1]) ? storedLanguage[1] : 'ko'; setLanguageState(nextLanguage); return i18n.changeLanguage(nextLanguage); }).catch(() => {}).finally(() => setHydrated(true)); }, []);
  const resolvedTheme = theme === 'system' ? (systemScheme === 'dark' ? 'dark' : 'light') : theme;
  const setTheme = (value) => { const next = ['system', ...Object.keys(THEMES)].includes(value) && isSeasonalThemeAvailable(value) ? value : 'system'; setThemeState(next); AsyncStorage.setItem('appTheme', next).catch(() => {}); };
  const toggleTheme = () => setTheme(resolvedTheme === 'dark' ? 'light' : 'dark');
  const setLanguage = async (value) => { const next = ['ko', 'en', 'zh', 'ja'].includes(value) ? value : 'ko'; await i18n.changeLanguage(next); setLanguageState(next); AsyncStorage.setItem('appLanguage', next).catch(() => {}); };
  const value = useMemo(() => ({ theme, resolvedTheme, isDark: ['dark', 'ocean', 'nightSea', 'halloween', 'christmas'].includes(resolvedTheme), colors: THEMES[resolvedTheme] || lightTheme, language, setTheme, toggleTheme, setLanguage, isSeasonalThemeAvailable, t: (key, options) => i18n.t(legacyKeys[key] || key, options), hydrated }), [theme, resolvedTheme, language, hydrated]);
  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
}
export function useAppSettings() { const context = useContext(AppSettingsContext); if (!context) throw new Error('useAppSettings must be used inside AppSettingsProvider'); return context; }
