import React, { useState } from 'react';
import { Alert, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './AuthContext';
import { useTranslation } from 'react-i18next';

const USERS_KEY = 'localUsers';
export default function AuthScreen({ navigation }) {
  const { t } = useTranslation(); const { signIn } = useAuth();
  const [mode, setMode] = useState('login'); const [userId, setUserId] = useState(''); const [password, setPassword] = useState(''); const [passwordConfirm, setPasswordConfirm] = useState(''); const [submitting, setSubmitting] = useState(false);
  const validate = () => { const id = userId.trim(); if (!id || !password) { Alert.alert(t('auth.inputTitle'), t('auth.inputRequired')); return false; } if (!/^[a-zA-Z0-9_@.-]{2,30}$/.test(id)) { Alert.alert(t('auth.inputTitle'), t('auth.idFormat')); return false; } if (password.length < 4) { Alert.alert(t('auth.passwordTitle'), t('auth.passwordRequired')); return false; } if (mode === 'signup' && password !== passwordConfirm) { Alert.alert(t('auth.passwordTitle'), t('auth.passwordMismatch')); return false; } return true; };
  const submit = async () => { if (!validate()) return; const id = userId.trim(); setSubmitting(true); try { const users = JSON.parse((await AsyncStorage.getItem(USERS_KEY)) || '[]'); if (mode === 'signup') { if (users.some((account) => account.userId.toLowerCase() === id.toLowerCase())) throw new Error(t('auth.duplicateId')); await AsyncStorage.setItem(USERS_KEY, JSON.stringify([...users, { userId: id, password }])); } else { const account = users.find((item) => item.userId.toLowerCase() === id.toLowerCase() && item.password === password); if (!account) throw new Error(t('auth.invalidCredentials')); } await signIn(id); setPassword(''); setPasswordConfirm(''); navigation.replace('AppTabs'); } catch (error) { Alert.alert(mode === 'signup' ? t('auth.signupFailedTitle') : t('auth.loginFailedTitle'), error.message || t('common.retry')); } finally { setSubmitting(false); } };
  const changeMode = (next) => { setMode(next); setPassword(''); setPasswordConfirm(''); };
  return <SafeAreaView style={s.safe}><View style={s.container}><Ionicons name="water" size={64} color="#00B4D8" /><Text style={s.brand}>{t('common.brand')}</Text><Text style={s.subtitle}>{mode === 'login' ? t('auth.loginSubtitle') : t('auth.signupSubtitle')}</Text><View style={s.tabs}><Tab active={mode === 'login'} title={t('common.login')} onPress={() => changeMode('login')} /><Tab active={mode === 'signup'} title={t('common.signup')} onPress={() => changeMode('signup')} /></View><Field icon="person-outline" value={userId} onChangeText={setUserId} placeholder={t('auth.idPlaceholder')} editable={!submitting} /><Field icon="lock-closed-outline" value={password} onChangeText={setPassword} placeholder={t('auth.passwordPlaceholder')} secureTextEntry editable={!submitting} />{mode === 'signup' && <Field icon="checkmark-circle-outline" value={passwordConfirm} onChangeText={setPasswordConfirm} placeholder={t('auth.confirmPasswordPlaceholder')} secureTextEntry editable={!submitting} />}<TouchableOpacity style={[s.submit, submitting && s.disabled]} onPress={submit} disabled={submitting}><Text style={s.submitText}>{submitting ? t('auth.processing') : mode === 'login' ? t('common.login') : t('common.signup')}</Text></TouchableOpacity><TouchableOpacity style={s.guest} onPress={() => navigation.replace('AppTabs')} disabled={submitting}><Text style={s.guestText}>{t('common.guest')}</Text></TouchableOpacity></View></SafeAreaView>;
}
function Tab({ active, title, onPress }) { return <TouchableOpacity onPress={onPress} style={[s.tab, active && s.tabActive]}><Text style={[s.tabText, active && s.tabTextActive]}>{title}</Text></TouchableOpacity>; }
function Field({ icon, ...props }) { return <View style={s.field}><Ionicons name={icon} size={19} color="#00B4D8" /><TextInput style={s.input} placeholderTextColor="#78909C" autoCapitalize="none" autoCorrect={false} {...props} /></View>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F0FAFC' }, container: { flex: 1, width: '100%', maxWidth: 540, alignSelf: 'center', justifyContent: 'center', padding: 25 }, brand: { color: '#0A192F', fontSize: 31, fontWeight: '900', textAlign: 'center', marginTop: 12 }, subtitle: { color: '#607D8B', textAlign: 'center', marginTop: 8, marginBottom: 22 }, tabs: { flexDirection: 'row', backgroundColor: '#DDEFF4', borderRadius: 13, padding: 4, marginBottom: 10 }, tab: { flex: 1, alignItems: 'center', borderRadius: 10, paddingVertical: 11 }, tabActive: { backgroundColor: '#FFF' }, tabText: { color: '#607D8B', fontWeight: '800' }, tabTextActive: { color: '#075985' }, field: { height: 54, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#D9EEF3', borderRadius: 13, paddingHorizontal: 14, alignItems: 'center', flexDirection: 'row', marginTop: 11 }, input: { flex: 1, color: '#0A192F', marginLeft: 9 }, submit: { backgroundColor: '#00B4D8', borderRadius: 14, padding: 17, alignItems: 'center', marginTop: 22 }, disabled: { opacity: 0.6 }, submitText: { color: '#062235', fontWeight: '900', fontSize: 16 }, guest: { alignItems: 'center', padding: 16, marginTop: 8 }, guestText: { color: '#075985', fontWeight: '800' } });
