import React, { useState } from 'react';
import { Alert, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './AuthContext';

export default function AuthScreen({ navigation }) { const { signIn } = useAuth(); const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [nickname, setNickname] = useState(''); const submit = async () => { if (!email.includes('@') || password.length < 6 || (mode === 'signup' && !nickname.trim())) return Alert.alert('입력 확인', '이메일, 6자 이상 비밀번호와 닉네임을 확인해 주세요.'); await AsyncStorage.setItem('hasSeenIntro', 'true'); await signIn({ nickname: mode === 'signup' ? nickname.trim() : '바다 탐험가' }); navigation.replace('AppTabs'); }; return <SafeAreaView style={styles.safe}><View style={styles.container}><TouchableOpacity style={styles.later} onPress={() => navigation.replace('AppTabs')}><Text style={styles.laterText}>나중에 하기</Text><Ionicons name="close" size={20} color="#607D8B" /></TouchableOpacity><Text style={styles.brand}>안 쏘고 뭐海</Text><View style={styles.tabs}><Tab active={mode === 'login'} text="로그인" onPress={() => setMode('login')} /><Tab active={mode === 'signup'} text="회원가입" onPress={() => setMode('signup')} /></View>{mode === 'signup' && <Input icon="person-outline" placeholder="닉네임" value={nickname} onChangeText={setNickname} />}<Input icon="mail-outline" placeholder="이메일" value={email} onChangeText={setEmail} /><Input icon="lock-closed-outline" placeholder="비밀번호 (6자 이상)" value={password} onChangeText={setPassword} secureTextEntry /><TouchableOpacity style={styles.submit} onPress={submit}><Text style={styles.submitText}>{mode === 'login' ? '로그인' : '가입하고 시작하기'}</Text></TouchableOpacity><Text style={styles.or}>또는</Text><Social icon="logo-google" text="Google로 계속하기" /><Social icon="chatbubble" text="카카오로 계속하기" /></View></SafeAreaView>; }
function Tab({ active, text, onPress }) { return <TouchableOpacity onPress={onPress} style={[styles.tab, active && styles.selected]}><Text style={styles.tabText}>{text}</Text></TouchableOpacity>; } function Input({ icon, ...props }) { return <View style={styles.inputWrap}><Ionicons name={icon} size={19} color="#00B4D8" /><TextInput style={styles.input} placeholderTextColor="#78909C" autoCapitalize="none" {...props} /></View>; } function Social({ icon, text }) { return <TouchableOpacity style={styles.social}><Ionicons name={icon} size={20} color="#0A192F" /><Text style={styles.socialText}>{text}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F0FAFC' }, container: { padding: 25, maxWidth: 540, width: '100%', alignSelf: 'center', marginTop: 45 }, later: { alignSelf: 'flex-end', flexDirection: 'row', gap: 4 }, laterText: { color: '#607D8B', fontWeight: '700' }, brand: { color: '#0A192F', fontWeight: '900', fontSize: 29, textAlign: 'center', marginBottom: 30 }, tabs: { flexDirection: 'row', backgroundColor: '#E2F3F7', borderRadius: 12, padding: 4, marginBottom: 22 }, tab: { flex: 1, alignItems: 'center', padding: 11, borderRadius: 9 }, selected: { backgroundColor: '#FFF' }, tabText: { color: '#0A192F', fontWeight: '800' }, inputWrap: { backgroundColor: '#FFF', borderRadius: 13, paddingHorizontal: 14, height: 54, alignItems: 'center', flexDirection: 'row', marginTop: 12 }, input: { flex: 1, color: '#0A192F', marginLeft: 9 }, submit: { backgroundColor: '#00B4D8', padding: 17, borderRadius: 14, alignItems: 'center', marginTop: 20 }, submitText: { color: '#0A192F', fontWeight: '900', fontSize: 16 }, or: { textAlign: 'center', color: '#607D8B', marginVertical: 16 }, social: { backgroundColor: '#FFF', flexDirection: 'row', justifyContent: 'center', gap: 9, padding: 15, borderRadius: 13, marginTop: 9 }, socialText: { color: '#0A192F', fontWeight: '700' } });
