import React, { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, Modal, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import marineData from './assets/marineData.json';

const VISION_MODELS = ['google/gemma-4-31b-it:free', 'google/gemma-4-26b-a4b-it:free', 'openrouter/free'];
const CATEGORIES = ['전체', '해파리', '어류', '산호/말미잘', '불가사리/성게', '갑각류', '연체동물', '해조류', '기타'];
const CATEGORY_KEYS = { '해파리': 'jellyfish', '어류': 'fish', '산호/말미잘': 'coral_anemone', '불가사리/성게': 'starfish_urchin', '갑각류': 'crustacean', '연체동물': 'mollusk', '해조류': 'seaweed', '기타': 'other' };
const KOREAN_NAMES = { 'marine_001': '노무라입깃해파리', 'marine_002': '보름달물해파리', 'marine_003': '파란고리문어', 'marine_004': '쏠배감펭', 'marine_005': '복섬', 'marine_006': '말미잘', 'marine_007': '보라성게', 'marine_008': '불가사리', 'marine_009': '꽃게', 'marine_010': '갯가재', 'marine_011': '참문어', 'marine_012': '뿔소라', 'marine_013': '홍합', 'marine_014': '미역', 'marine_015': '다시마', 'marine_016': '파래', 'marine_017': '톳', 'marine_018': '해삼', 'marine_019': '갯지렁이', 'marine_020': '해파리치레' };
const KOREAN_CATEGORIES = { jellyfish: '해파리', fish: '어류', coral_anemone: '산호/말미잘', starfish_urchin: '불가사리/성게', crustacean: '갑각류', mollusk: '연체동물', seaweed: '해조류', other: '기타' };
const KOREAN_DANGERS = { safe: '안전', caution: '주의', warning: '경계', severe: '심각' };
const KOREAN_DETAILS = {
  marine_001: ['황갈색의 대형 갓과 긴 구강완·촉수를 가진 해파리로, 여름부터 가을까지 남해와 동해 연안에서 출현합니다.', '절대 만지지 말고 쏘이면 바닷물로 세척한 뒤 촉수를 도구로 제거합니다.', ['황갈색 갓', '긴 구강완', '대형 원형 몸'], '보름달물해파리보다 크고 갓 중앙의 네 고리 무늬가 없습니다.', '7월~10월 · 표층~수심 10m · 남해 및 동해 연안', '자포 독성'],
  marine_002: ['투명한 갓 안에 네 개의 말발굽 모양 고리가 보이는 흔한 연안 해파리입니다.', '접촉을 피하고 피부에 닿으면 바닷물로 씻습니다.', ['투명한 갓', '네 개의 고리', '짧은 촉수'], '갓 중앙의 네 고리가 가장 뚜렷한 구별점입니다.', '4월~10월 · 표층~수심 5m · 전국 연안', '약한 자포 독성'],
  marine_003: ['자극을 받으면 파란 고리 무git add assets/marineData.json DictionaryScreen.js늬가 나타나는 작은 문어로 강한 신경독 위험이 있습니다.', '절대 만지지 말고 물렸다면 즉시 119에 신고합니다.', ['파란 고리 무늬', '작은 갈색 몸', '여덟 개의 팔'], '선명한 청색 고리 무늬가 일반 문어와 구분됩니다.', '5월~10월 · 조간대~수심 20m · 제주 및 남해', '복어독 계열 신경독'],
  marine_004: ['붉갈색 줄무늬와 부채 모양 지느러미, 독가시를 가진 어류입니다.', '맨손으로 잡지 말고 가시에 찔리면 의료기관 진료를 받습니다.', ['붉갈색 줄무늬', '부채 지느러미', '긴 등지느러미 가시'], '사자갈기처럼 펼쳐지는 긴 가시 지느러미가 특징입니다.', '연중 · 암반 수심 1m~30m · 제주 및 남해', '독가시'],
  marine_005: ['위험할 때 몸을 둥글게 부풀리는 복어류로 내장과 난소에 강한 독이 있을 수 있습니다.', '개인이 손질하거나 섭취하지 않으며 저림 증상은 즉시 119에 신고합니다.', ['둥근 몸', '점무늬', '부풀린 형태'], '몸 전체를 공처럼 부풀리고 작은 부리를 가집니다.', '봄~가을 · 조간대~수심 10m · 전국 연안', '복어독'],
  marine_006: ['바위에 붙어 꽃처럼 촉수를 펼치는 자포동물입니다.', '촉수를 만지지 말고 접촉하면 바닷물로 세척합니다.', ['꽃 모양 촉수', '원통형 몸', '암반 부착'], '바위에 고정되어 있어 자유롭게 헤엄치는 해파리와 다릅니다.', '연중 · 조간대~수심 15m · 암반 연안', '자포 독성'],
  marine_007: ['검보라색의 둥근 몸에 촘촘한 가시가 난 성게입니다.', '밟지 말고 가시가 깊게 박히면 진료를 받습니다.', ['보라색 구형 몸', '긴 가시', '암반 위 분포'], '별 모양 불가사리와 달리 가시가 난 구형입니다.', '연중 · 조간대~수심 20m · 제주 및 남해', '가시 손상 위험'],
  marine_008: ['보통 다섯 개의 팔을 가진 별 모양 극피동물입니다.', '관찰 후 서식지에 두고 오래 꺼내 두지 않습니다.', ['다섯 개의 팔', '별 모양', '거친 표면'], '성게와 달리 방사형 팔이 뚜렷합니다.', '연중 · 조간대~수심 30m · 전국 연안', '비독성·안전'],
  marine_009: ['넓은 등딱지와 강한 집게를 가진 대표적인 연안 게입니다.', '등딱지 뒤쪽을 잡아 집게를 피하고 상처는 세척합니다.', ['넓은 등딱지', '푸른빛 다리', '강한 집게'], '마지막 다리가 노처럼 납작해 헤엄칩니다.', '봄~가을 · 수심 1m~30m · 서해 및 남해', '집게 손상 위험'],
  marine_010: ['길쭉한 몸과 강한 앞다리를 가진 갯벌 갑각류입니다.', '장갑과 도구로 채집하고 앞다리에 찔리지 않도록 합니다.', ['길쭉한 마디 몸', '큰 앞다리', '모래색 등'], '새우보다 앞다리가 크고 몸이 납작합니다.', '봄~가을 · 모래바닥 수심 5m~50m · 서해 및 남해', '가시 손상 위험'],
  marine_011: ['여덟 팔과 흡반을 가지고 색을 바꾸며 암반 틈에 숨는 두족류입니다.', '억지로 잡지 말고 물린 상처는 세척·소독합니다.', ['여덟 개의 팔', '흡반', '색 변화 피부'], '파란 고리 무늬가 없고 일반적으로 더 큽니다.', '연중 · 암반 수심 1m~100m · 전국 연안', '물림 손상 위험'],
  marine_012: ['뿔 모양 돌기가 난 두꺼운 나선형 껍데기의 복족류입니다.', '내장과 침샘 부위를 제거하고 충분히 조리합니다.', ['나선형 껍데기', '뿔 돌기', '두꺼운 껍질'], '전복과 달리 껍데기에 뿔 같은 돌기가 있습니다.', '연중 · 암반 수심 1m~20m · 제주 및 남해', '내장 독성 가능성'],
  marine_013: ['검푸른 길쭉한 두 장 껍데기를 가진 이매패류입니다.', '패류독소 경보와 채취 금지 구역을 확인합니다.', ['검푸른 껍데기', '길쭉한 타원형', '군집 부착'], '굴보다 껍데기가 매끈하고 길며 짙은 청색입니다.', '연중 · 조간대~수심 10m · 전국 연안', '패류독소·오염 위험'],
  marine_014: ['중앙 줄기와 주름진 넓은 갈색 잎을 가진 대표 해조류입니다.', '오염 해역 채취를 피하고 신선도를 확인합니다.', ['갈색 넓은 잎', '중앙 줄기', '물결 주름'], '다시마보다 가장자리가 더 주름지고 중앙 줄기가 뚜렷합니다.', '겨울~봄 · 조간대~수심 15m · 암반 연안', '비독성·안전'],
  marine_015: ['넓고 두꺼운 갈색 띠 모양 잎이 길게 자라는 갈조류입니다.', '부패 냄새와 오염 여부를 확인한 뒤 취급합니다.', ['긴 갈색 띠', '두꺼운 잎', '매끈한 가장자리'], '미역보다 두껍고 긴 띠 형태이며 주름이 적습니다.', '겨울~봄 · 수심 2m~20m · 동해 및 남해', '비독성·안전'],
  marine_016: ['얇고 밝은 녹색 막처럼 보이는 녹조류입니다.', '악취나 오염이 의심되는 해역의 개체는 섭취하지 않습니다.', ['밝은 녹색', '얇은 막', '불규칙한 잎'], '갈색 해조류와 달리 선명한 녹색의 얇은 막입니다.', '봄~가을 · 조간대~수심 2m · 전국 연안', '오염·부패 주의'],
  marine_017: ['작은 기포와 가는 가지가 많은 갈조류입니다.', '안전 기준 제품을 이용하고 과도한 섭취를 피합니다.', ['가는 가지', '작은 공기주머니', '짙은 갈색'], '넓은 잎 대신 잔가지와 기포가 많은 것이 특징입니다.', '겨울~봄 · 조간대~수심 10m · 남해 및 제주', '무기비소 섭취 주의'],
  marine_018: ['부드러운 원통형 몸과 작은 돌기를 가진 극피동물입니다.', '관찰 후 제자리에 두고 채취 규정을 확인합니다.', ['원통형 몸', '표면 돌기', '느린 이동'], '팔이 없고 길쭉한 오이 형태입니다.', '연중 · 수심 1m~40m · 전국 연안', '비독성·안전'],
  marine_019: ['여러 마디와 양옆의 강모가 있는 갯벌 다모류입니다.', '장갑을 사용하고 피부에 박힌 강모는 조심스럽게 제거합니다.', ['마디진 몸', '양옆 강모', '적갈색'], '지렁이보다 양옆에 뚜렷한 강모가 있습니다.', '연중 · 갯벌 표층~수심 1m · 서해 및 남해 갯벌', '강모 피부 자극'],
  marine_020: ['유백색 또는 연한 갈색의 반구형 갓과 굵은 구강완을 가진 해파리입니다.', '살아 있는 개체는 만지지 말고 접촉 시 바닷물로 세척합니다.', ['유백색 반구형 갓', '굵은 구강완', '짧은 촉수'], '노무라입깃해파리보다 작고 촉수가 짧으며 색이 옅습니다.', '여름~가을 · 표층~수심 10m · 서해 및 남해', '약한 자포 독성']
};
const DATABASE = marineData.map((item) => { const [description, actionGuide, aiVisualFeatures, distinguishingPoints, habitatText, toxinType] = KOREAN_DETAILS[item.id]; const [season, depth, region] = habitatText.split(' · '); return { ...item, name: KOREAN_NAMES[item.id], category: KOREAN_CATEGORIES[item.category], dangerLevel: KOREAN_DANGERS[item.dangerLevel], description, actionGuide, aiVisualFeatures, distinguishingPoints, habitatInfo: { season, depth, region }, toxinType }; });
const DANGER_COLORS = { 안전: '#15803D', 주의: '#B45309', 경계: '#C2410C', 심각: '#B91C1C' };
const AI_PROMPT = '사진 속 해양 생물을 분석하고 JSON만 반환해: {"name":"한국어 이름","scientificName":"학명","dangerLevel":"안전|주의|경계|심각","description":"특징","actionGuide":"대처"}';

export default function DictionaryScreen() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('전체'); const [selected, setSelected] = useState(null);
  const [imageUri, setImageUri] = useState(null); const [loading, setLoading] = useState(false); const [aiResult, setAiResult] = useState(null);
  const filtered = useMemo(() => { const keyword = query.trim().toLowerCase(); return DATABASE.filter((item) => (category === '전체' || item.category === category) && (!keyword || [item.name, item.scientificName, ...(item.aiVisualFeatures || [])].join(' ').toLowerCase().includes(keyword))); }, [query, category]);
  const renderItem = useCallback(({ item }) => <TouchableOpacity style={styles.item} onPress={() => setSelected(item)}><View style={styles.itemTop}><Text style={styles.itemName}>{displayName(item)}</Text><Text style={[styles.danger, { color: DANGER_COLORS[item.dangerLevel] }]}>{item.dangerLevel}</Text></View><Text style={styles.category}>{item.category} · {item.scientificName}</Text><Text style={styles.description} numberOfLines={2}>{item.description}</Text><Text style={styles.featureLine}>AI 특징: {item.aiVisualFeatures?.join(' · ')}</Text></TouchableOpacity>, []);
  const pickImage = async (camera) => { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('권한 필요', '사진 접근 권한을 허용해 주세요.'); const response = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.7, base64: true }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.7, base64: true }); if (response.canceled) return; const asset = response.assets?.[0]; setImageUri(asset?.uri); await analyzeImage(asset?.base64, asset?.mimeType || 'image/jpeg'); };
  const analyzeImage = async (base64, mimeType) => { const key = process.env.EXPO_PUBLIC_OPENROUTER_API_KEY; if (!key || !base64) return Alert.alert('설정 오류', 'OpenRouter API 키 또는 이미지 데이터를 확인해 주세요.'); setLoading(true); try { let lastError = ''; for (const model of VISION_MODELS) { const response = await fetch('https://openrouter.ai/api/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model, response_format: { type: 'json_object' }, messages: [{ role: 'user', content: [{ type: 'text', text: AI_PROMPT }, { type: 'image_url', image_url: { url: `data:${mimeType};base64,${String(base64).replace(/^data:[^;]+;base64,/i, '')}` } }] }] }) }); if (!response.ok) { lastError = await response.text(); continue; } const data = await response.json(); const raw = String(data?.choices?.[0]?.message?.content || '').replace(/^\s*```json\s*/i, '').replace(/\s*```\s*$/, ''); const parsed = JSON.parse(raw); const local = findLocalEntry(parsed.name, parsed.scientificName); setAiResult({ ...parsed, ...(local ? { ...local, ...parsed, aiVisualFeatures: local.aiVisualFeatures, habitatInfo: local.habitatInfo, distinguishingPoints: local.distinguishingPoints, toxinType: local.toxinType } : {}) }); return; } throw new Error(lastError || '모든 AI 모델 분석에 실패했습니다.'); } catch (error) { Alert.alert('AI 분석 실패', '사진을 더 선명하게 촬영한 뒤 다시 시도해 주세요.'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><FlatList data={filtered} renderItem={renderItem} keyExtractor={(item) => item.id} initialNumToRender={12} maxToRenderPerBatch={12} windowSize={7} removeClippedSubviews={Platform.OS !== 'web'} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={styles.title}>해양 생물 도감</Text><Text style={styles.subtitle}>이름·학명·AI 시각 특징으로 검색하세요.</Text><View style={styles.search}><Ionicons name="search-outline" size={20} color="#00B4D8" /><TextInput style={styles.input} value={query} onChangeText={setQuery} placeholder="예: 노무라입깃해파리, 파란고리문어" placeholderTextColor="#78909C" /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{CATEGORIES.map((item) => <TouchableOpacity key={item} style={[styles.chip, category === item && styles.chipOn]} onPress={() => setCategory(item)}><Text style={styles.chipText}>{item}</Text></TouchableOpacity>)}</ScrollView><Text style={styles.count}>{filtered.length}종</Text></>} ListEmptyComponent={<Text style={styles.empty}>검색 결과가 없습니다.</Text>} ListFooterComponent={<ScannerPanel imageUri={imageUri} loading={loading} result={aiResult} onCamera={() => pickImage(true)} onLibrary={() => pickImage(false)} onDetail={() => setSelected(aiResult)} />} /><DetailModal item={selected} onClose={() => setSelected(null)} /></SafeAreaView>;
}

function displayName(item) { return item?.name || ''; }
function findLocalEntry(name = '', scientificName = '') { const normalized = name.replace(/\s/g, ''); return DATABASE.find((item) => item.name.replace(/\s/g, '') === normalized || scientificName && item.scientificName.toLowerCase() === scientificName.toLowerCase()); }
function ScannerPanel({ imageUri, loading, result, onCamera, onLibrary, onDetail }) { return <View style={styles.scanner}><Text style={styles.scannerTitle}>사진으로 AI 도감 찾기</Text>{imageUri ? <Image source={{ uri: imageUri }} style={styles.image} /> : <View style={styles.imagePlaceholder}><Ionicons name="camera-outline" size={35} color="#00B4D8" /></View>}<View style={styles.actions}><Button icon="camera-outline" text="카메라" onPress={onCamera} /><Button icon="images-outline" text="갤러리" onPress={onLibrary} /></View>{loading && <View style={styles.loading}><ActivityIndicator color="#00B4D8" /><Text style={styles.loadingText}>AI가 생물을 분석 중입니다...</Text></View>}{result && <TouchableOpacity style={styles.aiCard} onPress={onDetail}><Text style={styles.itemName}>{displayName(result)}</Text><Text style={styles.description}>{result.description}</Text>{result.aiVisualFeatures && <Text style={styles.featureLine}>연동된 AI 특징: {result.aiVisualFeatures.join(' · ')}</Text>}</TouchableOpacity>}</View>; }
function Button({ icon, text, onPress }) { return <TouchableOpacity style={styles.button} onPress={onPress}><Ionicons name={icon} size={20} color="#075985" /><Text style={styles.buttonText}>{text}</Text></TouchableOpacity>; }
function DetailModal({ item, onClose }) { if (!item) return null; const habitat = item.habitatInfo || {}; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><ScrollView contentContainerStyle={styles.modal}><View style={styles.modalHead}><View><Text style={styles.modalName}>{displayName(item)}</Text><Text style={styles.scientific}>{item.scientificName}</Text></View><TouchableOpacity onPress={onClose}><Ionicons name="close-circle" size={30} color="#607D8B" /></TouchableOpacity></View><Tag title="위험도" value={item.dangerLevel} /><Section title="설명" value={item.description} /><Section title="발견/접촉 시 대처" value={item.actionGuide} /><Section title="AI 시각 특징" value={(item.aiVisualFeatures || []).join(' · ') || '정보 없음'} /><Section title="유사 생물 구별법" value={item.distinguishingPoints || '정보 없음'} /><Section title="서식 정보" value={`${habitat.season || '정보 없음'} · ${habitat.depth || '정보 없음'} · ${habitat.region || '정보 없음'}`} /><Tag title="위험 유형" value={item.toxinType || '정보 없음'} /></ScrollView></View></Modal>; }
function Section({ title, value }) { return <View style={styles.detailSection}><Text style={styles.detailTitle}>{title}</Text><Text style={styles.detailText}>{value}</Text></View>; } function Tag({ title, value }) { return <View style={styles.tag}><Text style={styles.tagTitle}>{title}</Text><Text style={styles.tagValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F0FAFC' }, list: { padding: 20, paddingBottom: 42, maxWidth: 720, width: '100%', alignSelf: 'center' }, title: { fontSize: 27, fontWeight: '900', color: '#0A192F' }, subtitle: { color: '#607D8B', marginTop: 6 }, search: { height: 50, marginTop: 16, backgroundColor: '#FFF', borderRadius: 14, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center' }, input: { flex: 1, marginLeft: 8, color: '#0A192F' }, chips: { paddingVertical: 13, gap: 8 }, chip: { backgroundColor: '#DDF3F8', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 15 }, chipOn: { backgroundColor: '#00B4D8' }, chipText: { color: '#0A192F', fontSize: 12, fontWeight: '800' }, count: { color: '#607D8B', fontSize: 12, marginBottom: 2 }, item: { backgroundColor: '#FFF', borderRadius: 16, padding: 15, marginTop: 9 }, itemTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, itemName: { color: '#0A192F', fontWeight: '900', fontSize: 18, flex: 1 }, danger: { fontWeight: '900' }, category: { color: '#607D8B', fontSize: 12, marginTop: 5 }, description: { color: '#475569', lineHeight: 20, marginTop: 8 }, featureLine: { color: '#075985', fontSize: 12, lineHeight: 18, marginTop: 9, fontWeight: '700' }, empty: { textAlign: 'center', color: '#607D8B', marginVertical: 26 }, scanner: { marginTop: 30 }, scannerTitle: { color: '#0A192F', fontSize: 20, fontWeight: '900', marginBottom: 11 }, imagePlaceholder: { height: 135, alignItems: 'center', justifyContent: 'center', backgroundColor: '#DDF3F8', borderRadius: 16 }, image: { height: 180, borderRadius: 16 }, actions: { flexDirection: 'row', gap: 10, marginTop: 10 }, button: { flex: 1, backgroundColor: '#FFF', borderRadius: 13, padding: 13, flexDirection: 'row', justifyContent: 'center', gap: 6 }, buttonText: { color: '#075985', fontWeight: '800' }, loading: { backgroundColor: '#FFF', padding: 16, marginTop: 10, borderRadius: 14, alignItems: 'center' }, loadingText: { color: '#075985', fontWeight: '700', marginTop: 8 }, aiCard: { backgroundColor: '#E8F8FC', padding: 15, borderRadius: 16, marginTop: 12 }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(10,25,47,0.58)' }, modal: { backgroundColor: '#FFF', borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 23, maxHeight: '85%' }, modalHead: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, modalName: { color: '#0A192F', fontSize: 24, fontWeight: '900' }, scientific: { color: '#607D8B', fontStyle: 'italic', marginTop: 3 }, tag: { backgroundColor: '#DDF3F8', borderRadius: 13, padding: 12, marginTop: 15 }, tagTitle: { color: '#075985', fontSize: 12, fontWeight: '800' }, tagValue: { color: '#0A192F', fontWeight: '800', marginTop: 4 }, detailSection: { marginTop: 17 }, detailTitle: { color: '#0A192F', fontWeight: '900' }, detailText: { color: '#475569', lineHeight: 21, marginTop: 6 } });
