import React, { useMemo, useState } from 'react';
import { FlatList, Modal, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import marineData from './assets/marineData.json';
import { useAppSettings } from './AppSettingsContext';
import HeaderControls from './HeaderControls';

const CATEGORIES = ['전체', '해파리', '어류', '산호/말미잘', '불가사리/성게', '갑각류', '연체동물', '해조류', '기타'];
const categoryLabels = { 전체: ['전체', 'All', '全部', 'すべて'], 해파리: ['해파리', 'Jellyfish', '水母', 'クラゲ'], 어류: ['어류', 'Fish', '鱼类', '魚類'], '산호/말미잘': ['산호/말미잘', 'Coral / anemone', '珊瑚 / 海葵', 'サンゴ / イソギンチャク'], '불가사리/성게': ['불가사리/성게', 'Sea star / urchin', '海星 / 海胆', 'ヒトデ / ウニ'], 갑각류: ['갑각류', 'Crustaceans', '甲壳类', '甲殻類'], 연체동물: ['연체동물', 'Mollusks', '软体动物', '軟体動物'], 해조류: ['해조류', 'Seaweed', '海藻', '海藻'], 기타: ['기타', 'Other', '其他', 'その他'] };
const dangerLabels = { 안전: ['안전', 'Safe', '安全', '安全'], 관심: ['관심', 'Watch', '关注', '注意'], 주의: ['주의', 'Caution', '注意', '注意'], 경계: ['경계', 'Warning', '警戒', '警戒'], 심각: ['심각', 'Severe', '严重', '重大'], 경보: ['경보', 'Alert', '警报', '警报'] };
const indexFor = (language) => ({ ko: 0, en: 1, zh: 2, ja: 3 }[language] ?? 0);

export default function DictionaryScreen({ navigation }) {
  const { t, i18n } = useTranslation(); const { colors, language } = useAppSettings();
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('전체'); const [selected, setSelected] = useState(null);
  const languageIndex = indexFor(i18n.language || language);
  const getName = (item) => t(`encyclopedia.${item.id}.name`, { defaultValue: item.name });
  const getDescription = (item) => t(`encyclopedia.${item.id}.description`, { defaultValue: item.description });
  const getFirstAid = (item) => t(`encyclopedia.${item.id}.firstAid`, { defaultValue: item.actionGuide });
  const labelCategory = (value) => categoryLabels[value]?.[languageIndex] || value;
  const labelDanger = (value) => dangerLabels[value]?.[languageIndex] || value;
  const filtered = useMemo(() => { const word = query.trim().toLowerCase(); return marineData.filter((item) => (category === '전체' || item.category === category) && (!word || [getName(item), item.scientificName, ...(item.aiVisualFeatures || [])].join(' ').toLowerCase().includes(word))); }, [query, category, i18n.language]);
  const goBack = () => navigation?.canGoBack?.() ? navigation.goBack() : navigation?.navigate?.('Main');
  return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]}><FlatList data={filtered} keyExtractor={(item) => item.id} initialNumToRender={12} maxToRenderPerBatch={12} windowSize={7} removeClippedSubviews={Platform.OS !== 'web'} contentContainerStyle={s.list}
    ListHeaderComponent={<><View style={s.nav}><TouchableOpacity style={s.back} onPress={goBack}><Ionicons name="chevron-back" size={20} color={colors.accentStrong} /><Text style={[s.backText, { color: colors.accentStrong }]}>{t('common.back')}</Text></TouchableOpacity><View style={s.navRight}><HeaderControls /><TouchableOpacity style={[s.home, { backgroundColor: colors.soft }]} onPress={() => navigation.navigate('Main')}><Ionicons name="home-outline" size={17} color={colors.accentStrong} /><Text style={[s.homeText, { color: colors.accentStrong }]}>{t('common.home')}</Text></TouchableOpacity></View></View><Text style={[s.title, { color: colors.text }]}>{t('dictionary.title')}</Text><Text style={[s.subtitle, { color: colors.muted }]}>{t('dictionary.subtitle')}</Text><View style={[s.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Ionicons name="search-outline" size={20} color={colors.accent} /><TextInput style={[s.input, { color: colors.text }]} value={query} onChangeText={setQuery} placeholder={t('dictionary.searchPlaceholder')} placeholderTextColor={colors.muted} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{CATEGORIES.map((value) => <TouchableOpacity key={value} onPress={() => setCategory(value)} style={[s.filter, { backgroundColor: category === value ? colors.accent : colors.soft, borderColor: category === value ? colors.accent : colors.border }]}><Text style={[s.filterText, { color: category === value ? colors.onAccent : colors.text }]}>{labelCategory(value)}</Text></TouchableOpacity>)}</ScrollView><Text style={[s.count, { color: colors.muted }]}>{t('dictionary.count', { count: filtered.length })}</Text></>}
    renderItem={({ item }) => <TouchableOpacity style={[s.item, { backgroundColor: colors.surface, borderColor: colors.border }, Platform.OS === 'web' && { boxShadow: colors.shadow }]} onPress={() => setSelected(item)}><View style={s.itemTop}><Text style={[s.itemName, { color: colors.text }]} numberOfLines={2}>{getName(item)}</Text><Text style={[s.danger, { color: dangerColor(item.dangerLevel, colors) }]}>{labelDanger(item.dangerLevel)}</Text></View><Text style={[s.scientific, { color: colors.muted }]} numberOfLines={1}>{item.scientificName}</Text><Text style={[s.description, { color: colors.muted }]} numberOfLines={2}>{getDescription(item)}</Text><Text style={[s.detail, { color: colors.accentStrong }]}>{t('dictionary.detail')}</Text></TouchableOpacity>}
    ListEmptyComponent={<Text style={[s.empty, { color: colors.muted }]}>{t('dictionary.empty')}</Text>}
    ListFooterComponent={<TouchableOpacity style={[s.scannerLink, { backgroundColor: colors.soft }]} onPress={() => navigation.navigate('Scanner')}><Ionicons name="scan-outline" size={22} color={colors.accentStrong} /><View style={{ flex: 1 }}><Text style={[s.scannerTitle, { color: colors.text }]}>{t('tabs.scanner')}</Text><Text style={[s.scannerSub, { color: colors.muted }]}>{t('scanner.hint')}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.accentStrong} /></TouchableOpacity>}
  /><DetailModal item={selected} onClose={() => setSelected(null)} getName={getName} getDescription={getDescription} getFirstAid={getFirstAid} labelCategory={labelCategory} labelDanger={labelDanger} colors={colors} t={t} /></SafeAreaView>;
}
function DetailModal({ item, onClose, getName, getDescription, getFirstAid, labelCategory, labelDanger, colors, t }) { if (!item) return null; const key = `encyclopedia.${item.id}`; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={[s.backdrop, { backgroundColor: colors.backdrop }]}><ScrollView contentContainerStyle={[s.modal, { backgroundColor: colors.surface }]}><View style={s.modalHead}><View style={{ flex: 1 }}><Text style={[s.modalName, { color: colors.text }]}>{getName(item)}</Text><Text style={[s.scientific, { color: colors.muted }]}>{item.scientificName}</Text></View><TouchableOpacity onPress={onClose}><Ionicons name="close-circle" size={30} color={colors.muted} /></TouchableOpacity></View><Text style={[s.tag, { backgroundColor: colors.soft, color: colors.accentStrong }]}>{labelCategory(item.category)} · {labelDanger(item.dangerLevel)}</Text><Info title={t('dictionary.description')} value={getDescription(item)} colors={colors} /><Info title={t('dictionary.actionGuide')} value={getFirstAid(item)} colors={colors} /><Info title={t('dictionary.visualFeatures')} value={t(`${key}.visualFeatures`)} colors={colors} /><Info title={t('dictionary.distinguishing')} value={t(`${key}.distinguishing`)} colors={colors} /><Info title={t('dictionary.habitat')} value={t(`${key}.habitat`)} colors={colors} /><Info title={t('dictionary.toxin')} value={t(`${key}.toxin`)} colors={colors} /></ScrollView></View></Modal>; }
function Info({ title, value, colors }) { return <View style={s.section}><Text style={[s.sectionTitle, { color: colors.text }]}>{title}</Text><Text style={[s.sectionText, { color: colors.muted }]}>{value}</Text></View>; }
function dangerColor(level, colors) { return ['경계', '경보', '심각'].includes(level) ? colors.danger : level === '안전' ? colors.success : colors.warning; }
const s = StyleSheet.create({ safe: { flex: 1 }, list: { padding: 20, paddingBottom: 42 }, nav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, navRight: { flexDirection: 'row', alignItems: 'center', gap: 7 }, back: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7 }, backText: { fontWeight: '800' }, home: { flexDirection: 'row', alignItems: 'center', borderRadius: 13, paddingHorizontal: 10, paddingVertical: 7 }, homeText: { fontSize: 12, fontWeight: '800', marginLeft: 4 }, title: { fontSize: 27, fontWeight: '900', marginTop: 7 }, subtitle: { marginTop: 6 }, search: { height: 50, marginTop: 16, borderRadius: 14, borderWidth: 1, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center' }, input: { flex: 1, marginLeft: 8, minWidth: 0 }, filters: { gap: 8, paddingVertical: 13 }, filter: { minHeight: 38, borderRadius: 15, borderWidth: 1, paddingHorizontal: 12, justifyContent: 'center' }, filterText: { fontSize: 12, fontWeight: '800' }, count: { fontSize: 12, marginBottom: 2 }, item: { borderWidth: 1, borderRadius: 16, padding: 15, marginTop: 9 }, itemTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, itemName: { fontWeight: '900', fontSize: 18, flex: 1, flexShrink: 1 }, danger: { fontWeight: '900', fontSize: 13 }, scientific: { fontStyle: 'italic', marginTop: 4, flexShrink: 1 }, description: { lineHeight: 20, marginTop: 8, flexShrink: 1 }, detail: { fontWeight: '900', marginTop: 11 }, empty: { textAlign: 'center', marginVertical: 26 }, scannerLink: { borderRadius: 16, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 28 }, scannerTitle: { fontSize: 17, fontWeight: '900' }, scannerSub: { fontSize: 12, lineHeight: 18, marginTop: 4 }, backdrop: { flex: 1, justifyContent: 'flex-end' }, modal: { borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 23, maxHeight: '88%' }, modalHead: { flexDirection: 'row', gap: 12 }, modalName: { fontSize: 24, fontWeight: '900', flexShrink: 1 }, tag: { alignSelf: 'flex-start', overflow: 'hidden', borderRadius: 13, padding: 10, marginTop: 15, fontWeight: '800' }, section: { marginTop: 17 }, sectionTitle: { fontWeight: '900' }, sectionText: { lineHeight: 22, marginTop: 6, flexShrink: 1 } });
