import React, { useEffect, useState } from 'react';
import { Alert, SafeAreaView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './AuthContext';

export default function ProfileScreen({ navigation }) { const { user, isGuest, signOut } = useAuth(); const [alerts, setAlerts] = useState(true); const [scanCount, setScanCount] = useState(0); useEffect(() => { (async () => { setScanCount(JSON.parse(await AsyncStorage.getItem('scanHistory') || '[]').length); setAlerts((await AsyncStorage.getItem('riskAlerts')) !== 'false'); })(); }, []); const login = () => navigation.getParent()?.navigate('Auth'); const logout = () => Alert.alert('로그아웃', '로그아웃하시겠어요?', [{ text: '취소', style: 'cancel' }, { text: '로그아웃', style: 'destructive', onPress: async () => { await signOut(); login(); } }]); if (isGuest) return <SafeAreaView style={styles.safe}><View style={styles.container}><Ionicons name="person-circle-outline" size={78} color="#00B4D8" /><Text style={styles.guestTitle}>현재 게스트 모드로 이용 중입니다.</Text><Text style={styles.caption}>스캔 기록과 즐겨찾기를 안전하게 보관하려면 로그인해 주세요.</Text><TouchableOpacity style={styles.join} onPress={login}><Text style={styles.joinText}>3초 만에 회원가입 / 로그인하기</Text></TouchableOpacity><Text style={styles.version}>안 쏘고 뭐海 v1.0.0</Text></View></SafeAreaView>; return <SafeAreaView style={styles.safe}><View style={styles.container}><View style={styles.profile}><Ionicons name="person-circle" size={66} color="#00B4D8" /><View><Text style={styles.name}>{user.nickname} 님</Text><Text style={styles.caption}>안전한 바다 탐험을 응원해요</Text></View></View><View style={styles.stats}><Stat label="스캔" value={scanCount} /><Stat label="제보" value="0" /></View><View style={styles.card}><View style={styles.row}><View><Text style={styles.rowTitle}>해파리 출몰 위험 경보</Text><Text style={styles.caption}>관심 해수욕장 위험도 알림</Text></View><Switch value={alerts} onValueChange={async (v) => { setAlerts(v); await AsyncStorage.setItem('riskAlerts', String(v)); }} trackColor={{ true: '#00B4D8' }} /></View></View><Text style={styles.version}>안 쏘고 뭐海 v1.0.0</Text><TouchableOpacity style={styles.logout} onPress={logout}><Text style={styles.logoutText}>로그아웃</Text></TouchableOpacity></View></SafeAreaView>; }
function Stat({ label, value }) { return <View><Text style={styles.statValue}>{value}</Text><Text style={styles.caption}>{label}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F0FAFC' }, container: { flex: 1, padding: 20, maxWidth: 680, alignSelf: 'center', width: '100%', justifyContent: 'center' }, profile: { flexDirection: 'row', alignItems: 'center', gap: 13 }, name: { color: '#0A192F', fontSize: 22, fontWeight: '900' }, guestTitle: { color: '#0A192F', fontSize: 21, fontWeight: '900', marginTop: 16 }, caption: { color: '#607D8B', fontSize: 13, marginTop: 3 }, stats: { backgroundColor: '#FFF', borderRadius: 18, padding: 20, flexDirection: 'row', justifyContent: 'space-around', marginTop: 22 }, statValue: { textAlign: 'center', color: '#00B4D8', fontSize: 23, fontWeight: '900' }, card: { backgroundColor: '#FFF', borderRadius: 18, padding: 18, marginTop: 16 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, rowTitle: { color: '#0A192F', fontWeight: '800' }, join: { backgroundColor: '#00B4D8', padding: 17, borderRadius: 14, alignItems: 'center', marginTop: 25 }, joinText: { color: '#0A192F', fontWeight: '900' }, version: { color: '#78909C', textAlign: 'center', marginTop: 35, fontSize: 12 }, logout: { borderWidth: 1, borderColor: '#FF4D4D', borderRadius: 13, padding: 14, alignItems: 'center', marginTop: 18 }, logoutText: { color: '#FF4D4D', fontWeight: '800' } });
