import React, { useEffect, useState } from 'react';
import { SafeAreaView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './AuthContext';
import { useAppSettings } from './AppSettingsContext';
import { useTranslation } from 'react-i18next';

export default function ProfileScreen({ navigation }) {
  const { t } = useTranslation(); const { user, userId, isLoggedIn, signOut } = useAuth(); const { isDark, setTheme, language, setLanguage, colors: themeColors } = useAppSettings();
  const [alerts, setAlerts] = useState(true); const [scanCount, setScanCount] = useState(0); const [collectionCount, setCollectionCount] = useState(0);
  useEffect(() => { (async () => { setScanCount(JSON.parse((await AsyncStorage.getItem('scanHistory')) || '[]').length); setAlerts((await AsyncStorage.getItem('riskAlerts')) !== 'false'); if (user) setCollectionCount(JSON.parse((await AsyncStorage.getItem(`marineCollection_${userId}`)) || '[]').length); })(); }, [user, userId]);
  const login = () => navigation.getParent()?.navigate('Auth'); const home = () => navigation.navigate('Main');
  const logout = () => {
    // Do not rely on Alert callbacks: React Native Web can block or suppress
    // them. Clear the state immediately, then move directly to the login form.
    signOut().catch(() => {});
    const rootNavigation = navigation.getParent();
    if (rootNavigation) rootNavigation.navigate('Auth');
    else navigation.navigate('Auth');
  };
  const colors = { bg: themeColors.background, card: themeColors.surface, text: themeColors.text, sub: themeColors.muted };
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.bg }]}><View style={styles.container}><TouchableOpacity style={styles.home} onPress={home}><Ionicons name="home-outline" size={17} color="#075985" /><Text style={styles.homeText}>맨 처음 화면으로</Text></TouchableOpacity>{!isLoggedIn ? <><Ionicons name="person-circle-outline" size={78} color="#00B4D8" /><Text style={[styles.guestTitle, { color: colors.text }]}>로그인이 필요합니다.</Text><Text style={[styles.caption, { color: colors.sub }]}>개인 도감과 스캔 기록을 저장하려면 로그인해 주세요.</Text><TouchableOpacity style={styles.join} onPress={login}><Text style={styles.joinText}>아이디 / 비밀번호로 로그인하기</Text></TouchableOpacity></> : <><View style={styles.profile}><Ionicons name="person-circle" size={66} color="#00B4D8" /><View><Text style={[styles.name, { color: colors.text }]}>{userId} 님</Text><Text style={[styles.caption, { color: colors.sub }]}>로그인 상태 · 안전한 바다 탐험을 응원해요</Text></View></View><View style={[styles.stats, { backgroundColor: colors.card }]}><Stat label="스캔" value={scanCount} color={colors.sub} /><Stat label="내 도감" value={collectionCount} color={colors.sub} /></View></>}
    <View style={[styles.card, { backgroundColor: colors.card }]}><Row title={t('profile.alerts')} caption={t('profile.alertsCaption')} colors={colors}><Switch value={alerts} onValueChange={async (value) => { setAlerts(value); await AsyncStorage.setItem('riskAlerts', String(value)); }} trackColor={{ true: '#00B4D8' }} /></Row><Row title={t('common.darkMode')} caption={t('profile.themeCaption')} colors={colors}><Switch value={isDark} onValueChange={(value) => setTheme(value ? 'dark' : 'light')} trackColor={{ true: '#00B4D8' }} /></Row><Row title={t('common.language')} caption={t('profile.languageCaption')} colors={colors}><TouchableOpacity style={styles.language} onPress={() => setLanguage(language === 'ko' ? 'en' : 'ko')}><Text style={styles.languageText}>{language === 'ko' ? '한국어' : 'EN'}</Text></TouchableOpacity></Row></View><Text style={[styles.version, { color: colors.sub }]}>{t('profile.version')}</Text>{isLoggedIn && <TouchableOpacity style={styles.logout} onPress={logout}><Text style={styles.logoutText}>{t('common.logout')}</Text></TouchableOpacity>}</View></SafeAreaView>;
}
function Row({ title, caption, colors, children }) { return <View style={styles.row}><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.caption, { color: colors.sub }]}>{caption}</Text></View>{children}</View>; }
function Stat({ label, value, color }) { return <View><Text style={styles.statValue}>{value}</Text><Text style={[styles.caption, { color }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, container: { flex: 1, padding: 20, maxWidth: 680, alignSelf: 'center', width: '100%', justifyContent: 'center' }, home: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', backgroundColor: '#E0F2FE', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 13, marginBottom: 24 }, homeText: { color: '#075985', fontWeight: '800', marginLeft: 4, fontSize: 12 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 13 }, name: { fontSize: 22, fontWeight: '900' }, guestTitle: { fontSize: 21, fontWeight: '900', marginTop: 16 }, caption: { fontSize: 13, marginTop: 3 }, stats: { borderRadius: 18, padding: 20, flexDirection: 'row', justifyContent: 'space-around', marginTop: 22 }, statValue: { textAlign: 'center', color: '#00B4D8', fontSize: 23, fontWeight: '900' }, card: { borderRadius: 18, padding: 18, marginTop: 16 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 11 }, rowTitle: { fontWeight: '800' }, language: { backgroundColor: '#E0F2FE', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10 }, languageText: { color: '#075985', fontWeight: '900' }, join: { backgroundColor: '#00B4D8', padding: 17, borderRadius: 14, alignItems: 'center', marginTop: 25 }, joinText: { color: '#0A192F', fontWeight: '900' }, version: { textAlign: 'center', marginTop: 35, fontSize: 12 }, logout: { borderWidth: 1, borderColor: '#FF4D4D', borderRadius: 13, padding: 14, alignItems: 'center', marginTop: 18 }, logoutText: { color: '#FF4D4D', fontWeight: '800' } });
