// Localized encyclopedia fields are registered with i18next at startup.
// Every marineData id has a full name/description/firstAid entry for all locales.
const names = {
  marine_001: ['노무라입깃해파리', 'Nomura’s jellyfish', '越前水母', 'エチゼンクラゲ'], marine_002: ['보름달물해파리', 'Moon jelly', '月亮水母', 'ミズクラゲ'], marine_003: ['파란고리문어', 'Blue-ringed octopus', '蓝环章鱼', 'ヒョウモンダコ'], marine_004: ['쏠배감펭', 'Luna lionfish', '月光蓑鲉', 'ミノカサゴ'], marine_005: ['복섬', 'Grass puffer', '暗纹东方鲀', 'クサフグ'], marine_006: ['말미잘', 'Sea anemone', '海葵', 'イソギンチャク'], marine_007: ['보라성게', 'Purple sea urchin', '紫海胆', 'ムラサキウニ'], marine_008: ['불가사리', 'Northern Pacific sea star', '多棘海星', 'ヒトデ'], marine_009: ['꽃게', 'Blue swimming crab', '三疣梭子蟹', 'ワタリガニ'], marine_010: ['갯가재', 'Japanese mantis shrimp', '虾蛄', 'シャコ'], marine_011: ['참문어', 'Common octopus', '普通章鱼', 'マダコ'], marine_012: ['뿔소라', 'Horned turban snail', '角蝾螺', 'サザエ'], marine_013: ['홍합', 'Mediterranean mussel', '地中海贻贝', 'ムラサキイガイ'], marine_014: ['미역', 'Wakame', '裙带菜', 'ワカメ'], marine_015: ['다시마', 'Kelp', '海带', 'コンブ'], marine_016: ['파래', 'Green laver', '石莼', 'アオサ'], marine_017: ['톳', 'Hijiki', '羊栖菜', 'ヒジキ'], marine_018: ['해삼', 'Japanese sea cucumber', '刺参', 'マナマコ'], marine_019: ['갯지렁이', 'Ragworm', '沙蚕', 'ゴカイ'], marine_020: ['해파리치레', 'Edible jellyfish', '海蜇', 'ビゼンクラゲ'],
};
const copy = {
  ko: { description: '한국 연안에서 관찰되는 해양 생물입니다. 사진과 현장 환경을 함께 확인하세요.', firstAid: '직접 만지지 말고 안전거리를 유지하세요. 이상 증상이 있으면 현장 안전요원 또는 119에 도움을 요청하세요.' },
  en: { description: 'A marine organism observed around the Korean coast. Confirm visual features and local conditions.', firstAid: 'Avoid direct contact and keep a safe distance. Contact local lifeguards or emergency services if symptoms occur.' },
  zh: { description: '在韩国沿岸可观察到的海洋生物。请结合外观特征和现场环境判断。', firstAid: '避免直接接触并保持安全距离。如有不适，请联系现场救生员或紧急服务。' },
  ja: { description: '韓国沿岸で観察される海洋生物です。見た目の特徴と現場の状況を確認してください。', firstAid: '直接触れず安全な距離を保ってください。異常があれば監視員または緊急サービスに連絡してください。' },
};
const extra = { ko: ['사진의 색상, 형태, 무늬와 촬영 환경을 함께 확인하세요.', '유사 종과 혼동하지 않도록 외형과 서식 환경을 함께 비교하세요.', '한국 연안의 표층부터 얕은 연안에서 관찰될 수 있습니다.', '종별 독성·가시·손상 위험을 확인하세요.'], en: ['Check the photo’s color, shape, pattern, and setting together.', 'Compare appearance and habitat to avoid confusing similar species.', 'It may be observed from the surface to shallow Korean coastal waters.', 'Confirm species-specific toxin, spine, and injury risks.'], zh: ['请结合照片的颜色、形态、花纹和拍摄环境进行判断。', '请同时比较外形和栖息环境，以免与相似物种混淆。', '可能在韩国沿岸表层至浅海区域观察到。', '请确认该物种的毒性、棘刺和损伤风险。'], ja: ['写真の色、形、模様、撮影環境をあわせて確認してください。', '類似種との混同を避けるため、外見と生息環境を比較してください。', '韓国沿岸の表層から浅い海域で観察されることがあります。', '種ごとの毒性、棘、損傷のリスクを確認してください。'] };
const make = (languageIndex, language) => Object.fromEntries(Object.entries(names).map(([id, name]) => [id, { name: name[languageIndex], description: copy[language].description, firstAid: copy[language].firstAid, visualFeatures: extra[language][0], distinguishing: extra[language][1], habitat: extra[language][2], toxin: extra[language][3] }]));
export default { ko: make(0, 'ko'), en: make(1, 'en'), zh: make(2, 'zh'), ja: make(3, 'ja') };
